spring:
  application:
    name: SportLife-API

  datasource:
    url: jdbc:postgresql://localhost:5432/sportlife_db
    username: postgres
    password: javaburger
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: PENDIENTE
            client-secret: PENDIENTE
            scope:
              - email
              - profile


jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 3600000